import { Floorplan } from './floorplan.model';
import { Parking } from './parking.model';
import { SchoolsInfo } from './school-info.model';
import { PetInfo } from './pet-info.model';
import { Geocode } from './geocode.model';

export interface PropertyModel {
  listID: number;
  propertyID: number;
  yearBuilt: number;
  yearRenovated: number;
  name: string;
  streetAddress: string;
  phone: string;
  city: string;
  adminFee: number;
  appFee: number;
  url: string;
  favorite: boolean;
  notes: string;
  displayNotes?: string;
  specials: string;
  parking: Parking;
  schoolsInfo: SchoolsInfo;
  petInfo: PetInfo;
  petOptions: any;
  parkingOptions: any;
  paidUtilities: any[];
  state: string;
  floorplans: Floorplan[];
  highValueAmenities: string[];
  unitAmenities: string[];
  propertyAmenities: string[];
  geocode: Geocode;
  photos: string[];
  section8: boolean;
  studentHousting: boolean;
  seniorHousing: boolean;
  officeHours: null;
  numUnits: number;
  email: null;
  role: string;
  management: null;
  managementOffices: any[];
  regionalName: null;
  regionalPhone: null;
  regionalEmail: null;
  onsiteManager: null;
}
